downforacross/downforacross.com

- src/components/fileUploader.css
- src/components/fileUploader.js
- src/components/upload.css
- src/components/upload.js
- src/containers/welcome.css
- src/containers/welcome.js
Redesigning the landing page!
* No more ugly gray colors
* Blue header thing
* More elegant puzzle entries on the welcome page
* Prettier upload box (bigger)
* No more scrolling on home page!
Now that the home page doesn't look terrible we can start adding home-links from the game pages.
> Redesign welcome page

- public/names.js
> New name suggestions

- src/components/GridControls.js
I tested this locally. Not sure if you have more extensive testing requirements.
> Delete current letter on delete keydown

- src/pages/Replays.js
- src/pages/css/replays.css
#23 modified styles a bit. Didn't fix the header issue, cause there was no explanation of how it should work :).
> replays page needs a redesign #23 

- src/components/GridControls.js
> Allow delete to skip over correct characters

- src/lib/emojiPacks/custom.js
> Add steven

- src/actions.js
- src/components/Cell.js
- src/components/ChatV2.js
- src/components/Game.js
- src/components/Grid.js
- src/components/Player.js
- src/components/Powerups.js
- src/components/css/powerups.css
- src/index.js
- src/lib/emojiPacks/custom.js
- src/lib/powerups.js
- src/pages/Battle.js
- src/pages/GameV2.js
- src/pages/Play.js
- src/pages/css/battle.css
- src/pages/index.js
- src/store/battle.js
- src/store/game.js
- src/store/index.js
- src/store/puzzle.js
- src/utils/GameOperations.js
- src/utils/Grid.js
> Battle mode v0

- src/components/GridControls.js
I would have added for mobile but screen real estate is valuable - Should this just replace the swipe left/right behavior or something?
> Add forward/back controls on web

- src/components/Toolbar.js
downforacross is a great website! TIL about the pencil tool and it makes my solves way easier
> Fix "Shortuct" typo

- src/components/Chat/css/index.css
- src/components/Chat/index.js
Example with note:
Example without note:
> Render note / description in puzzles that have them

- package.json
- src/components/Game/Confetti.js
- src/components/Game/Game.js
- yarn.lock
Displays confetti for 7 seconds whenever the game goes from being unsolved to solved. Doesn't show on mobile to avoid performance issues.
Just an idea. Feel free to take or leave. :)
> Display celebratory confetti on solve

- src/pages/Game.js
- src/store/game.js
follow-up to https://github.com/downforacross/downforacross.com/pull/107
- turns on ws by default (no opt-out)
- stops sending game events to firebase
> turn off firebase events

- src/lib/wrappers/HistoryWrapper.js
- src/pages/Game.js
- src/store/game.js
this probably fixes https://github.com/downforacross/downforacross.com/issues/110
> fix websocket reconnect

- README.md
www.downforacross.com does not resolve.
> Fix URL typo in README

- server/SocketManager.ts
- server/model/game.ts
- server/model/room.ts
- server/sql/create_room_events.sql
- src/store/game.js
part 1 of https://github.com/downforacross/downforacross.com/pull/142
- deploy backend before frontend
> backend for rooms

- server/SocketManager.ts
- src/components/Fencing/Fencing.tsx
- src/components/Fencing/transformGameStateToPlayerProps.ts
- src/components/Fencing/transformGameToPlayerProps.ts
- src/components/Fencing/usePlayerActions.ts
- src/index.js
- src/lib/reducers/gameV2.ts
- src/lib/reducers/room.ts
- src/pages/Fencing.tsx
- src/pages/index.js
- src/shared/gameEvents.ts
- src/shared/roomEvents.ts
- src/shared/types.ts
This PR is part 1 of https://github.com/downforacross/downforacross.com/pull/145.
No real fencing game logic has been written yet, but this sets the stage for it by adding a bunch of scaffolding & doing some refactoring.
- src/lib/reducers/gameV2.ts -- a ts version of reducers/game.js
- use the game event schema as the current one to be backwards compatible
- use a slightly different (a subset in terms of functionality) game state definition to allow for gradual migration of js->ts
- to be used for just fencing initially, but intended to replace
game.js eventually
- Fencing.tsx -- react entrypoint for all the fencing-related UI
- also added a bunch of ts & related scaffolding for GameEvent
interface
Part 2 will contain the bulk of the implementation of game logic -- all the reducers for …
> fencing pt 1

- src/components/Game/Game.js
- src/components/Grid/Cell.tsx
- src/components/Grid/Grid.tsx
- src/components/Grid/types.ts
- src/components/Player/Player.js
- src/components/Toolbar/index.js
- src/lib/colors.js
- src/lib/reducers/game.js
- src/store/game.js
> Color attribution by user mode

- package.json
- server/api/puzzle_list.ts
- server/model/puzzle.ts
- server/model/stats.ts
- server/sql/create_puzzles.sql
- src/api/puzzle_list.ts
- src/components/PuzzleList/Entry.tsx
- src/components/PuzzleList/NewPuzzleList.tsx
- src/components/PuzzleList/PuzzleList.js
- src/shared/types.ts
- yarn.lock
- move filtering to postgres query
- move postgres to jsonb to be able to query faster (indexes coming soon too)
- revamp NewPuzzleList.tsx to change query based on new filters and fetch more with scrolling
> [PostgresPuzzleList 1/N] Move puzzle listing to use postgres

- src/components/Toolbar/ActionMenu.js
> Dropdown outside click

- src/components/Fencing/Fencing.tsx
- src/components/Fencing/FencingScoreboard.tsx
- src/components/Fencing/css/fencingScoreboard.css
> Current user

- src/components/Fencing/Fencing.tsx
Just wrapped the entire fencing element around a `<Flex>` and added a `<Nav>` component.
Address "Banner at the top that goes back to the main site" from #172.
> Add top nav bar for fencing mode

- src/components/Grid/Cell.tsx
- src/components/Player/Player.js
- src/shared/types.ts
This PR makes it possible to hover over cursors with your mouse and see which players are on that cell. Requested in #65
> Implement cursor hover to show player(s) on grid

- src/components/Player/GridControls.js
Please let me know if I'm doing this right. I have zero web dev or open source experience
Also would love to help contribute more (preferably something small and easy for a beginner), like fleshing out the vim functionality a bit more
> Adding 's' functionality in vim mode

- src/components/Chat/Chat.js
- src/components/Chat/css/index.css
- src/pages/Game.js
It is not 100% intuitive on how to play a game with your friends. This message in the chat should hopefully make it easier for newcomers to figure out how to collaborate with others on a puzzle.
> Add system chat message with game link

- src/components/Fencing/Fencing.tsx
- src/components/Fencing/FencingScoreboard.tsx
- src/components/Fencing/transformGameToPlayerProps.ts
- src/components/Fencing/usePlayerActions.ts
- src/components/Grid/Grid.tsx
- src/components/Grid/types.ts
- src/shared/gameEvents/allEventDefs.ts
- src/shared/gameEvents/eventDefs/check.ts
- src/shared/gameEvents/eventDefs/reveal.ts
- src/shared/gameEvents/eventDefs/startGame.ts
- src/shared/gameEvents/eventDefs/updateCell.ts
- src/shared/gameEvents/eventDefs/updateDisplayName.ts
- src/shared/gameEvents/eventDefs/updateTeamName.ts
- src/shared/gameEvents/initialState.ts
- src/shared/gameEvents/types/GameState.ts
- src/shared/types.ts
And hopefully will also get to these:
> fencing ux v2

- src/lib/jsUtils.js
Reverts downforacross/downforacross.com#195
> Revert "iPad OS no longer reports platform as iPad, by default"

- src/components/Grid/css/cell.css
- src/components/Toolbar/css/index.css
- src/components/Toolbar/index.js
- src/style.css
Adds a color picker to the pencil tool.
> Add color picker to pencil tool

- src/components/Chat/Chat.js
- src/components/Chat/css/index.css
Add timestamps to chat messages.
Addresses #175.
> Add timestamps to chat messages

- src/components/Player/GridControls.js
- src/components/Player/ListViewControls.tsx
- src/components/Player/MobileListViewControls.tsx
- src/components/Toolbar/index.js
- src/lib/wrappers/GridWrapper.js
Implement these buttons so that they go to the beginning or end of a
clue, respectively.
> Implement Home and End buttons

- src/index.js
Updated Welcome route (index.js line 76) to WrappedWelcome to solve issue of user being directed to a blank page
> Update Welcome route

- src/api/create_game.ts
- src/components/Chat/Chat.js
- src/components/Player/MobileListViewControls.tsx
- src/components/Timeline/Timeline.js
- src/components/Upload/FileUploader.js
- src/shared/fencingGameEvents/eventDefs/startGame.ts
when game is finished, this appears in chatbox:
what gets copied to clipboard:
```
I solved NY Times, Wednesday, April 24, 2024 in 00:28!
http://localhost:3020/beta/play/34343
```
note that this is a link to create a new game with the same puzzle, not a link to the existing game.
> Add share score when game is finished

- src/components/Chat/Chat.js
- src/components/Game/Game.js
- src/pages/Game.js
Allows user to click on clue references and go to the matching clue. Implements #304.
Would definitely appreciate feedback on UI, I simply just converted it into a button to make it stand out, but something else could be done as well.
> Clickable clue references
