downforacross/downforacross.com

src/components/Upload.js
This change adds a second button to the .puz file Upload component shown after choosing a .puz file. The second button also creates a new puzzle but it sets `private: true` so the puzzle does not appear in the public list of puzzles. After the database transaction, it shows a message to the user with a link to the /beta/play/<pid> url to start a new game with the uploaded puzzle.
=> Add a button to .puz uploader to create unlisted (url only) puzzles

src/components/Chat/css/index.css, src/components/Chat/index.js, src/components/Game/index.js, src/components/Player/index.js, src/lib/reducers/game.js, src/pages/Game.js, src/store/game.js
Changes:
- displays user presented under chat bar, with reasonable wrapping if name is too long
- moves user information (color, displayname) to a single object in the reducer
- messages now show current name corresponding to each sender (instead of the sender name at the time of message sent)
=> Display user presented under chat bar

src/components/Toolbar/Popup.js, src/components/Toolbar/css/Popup.css, src/components/Toolbar/css/index.css, src/components/Toolbar/index.js
**What**
Basing off of a discussion had on #85 I realized it might be nice to have instructions on how to use the app for future people curious on how to answer rebuses. This PR makes a modal for instructions on app usage and [specifically calls out the rebus functionality](https://github.com/downforacross/downforacross.com/compare/master...ibrand:info-button-with-instructions?expand=1#diff-03812c996752ae5efb2018ea2f2fc260R141).
Happy to make changes to this or for you to just take inspiration for it if you want to add something else.
**Screenshot of functionality:**
=> Add an info button with the rules for how to use the app

src/components/Chat/ChatBar.js, src/components/Chat/css/index.css
Looks like this was from when we removed the custom mobile
keyboard, but didn't make sure the default keyboard would
get rendered instead.
This just subs the mobile EditableSpan with a regular old
input. Except I added some styling to keep it more
consistent with how the current mobile chat input looks.
=> Fix issue where mobile chat didn't bring up a keyboard.

package.json, src/components/Chat/Chat.js, src/components/Player/MobileGridControls.js, src/components/Player/css/mobileGridControls.css, src/components/PuzzleList/Entry.js, src/components/PuzzleList/css/puzzleList.css, src/components/Toolbar/css/ActionMenu.css, src/components/Toolbar/css/index.css, src/components/Toolbar/index.js, src/components/Upload/FileUploader.js, src/components/Upload/css/fileUploader.css, src/pages/Welcome.js, src/pages/css/welcome.css, yarn.lock
- Size mobile toolbars for touch targets (≥ 48px)
- Remove second clue bar on mobile (is there a reason for it?)
- Replace most icons with [Material icon set](https://material.io/resources/icons/?style=baseline) to improve visuals and simplify code
=> Mobile UI improvements + Material icons

src/components/Game/Game.js, src/components/Player/GridControls.js, src/components/Player/Player.js, src/components/Toolbar/index.js
This is more of a proof of concept (the actual code needs more cleanup work and there are some design questions that need to be addressed here), but I've managed to implement vim keybindings to the frontend. My changes adds a new action menu which allows you to switch from normal mode to vim mode. Vim mode should allow `hjkl` for navigation and `x` for deleting in normal mode, and all the original action keys from insert mode. To switch into insert mode use `i` and to switch back to normal mode use `Escpape`. If you could look at it and tell me what you think, that'd be great :).
=> Vim Keybindings

src/components/PuzzleList/PuzzleList.js
Instead of the current (confusing) filter behaviour, we instead:
* Lower case the search string
* Split it into tokens
Then, each token must be present within the (lowercase) author name, or puzzle title or it is filtered out.
This is a draft PR until I can actually test it (see #116)
Closes #92.
=> Use a tokenizing filter

src/dark.css, src/style.css
Makes use of the same font family in the search bar, chat, and buttons. Arial (or the default input font on a browser) is too noticeable among the various text renderings.
Makes dark theme use the same outline shape on inputs for consistency. This makes the full bounding box seen on dark theme (in line with the light theme).
=> Unify font styling across app and light and dark themes

src/lib/names.js
The following adjectives were duplicated in the names module as per the following listing:
```
2 Zero-tolerant
2 Zealous
2 Visible
2 Unique
2 Temperate
2 Natural
2 Jealous
2 Critical
2 Anxious
```
This change removes the duplicated adjectives to ensure name frequency is balanced across all adjectives.
This change also cleans up some inconsistent capitalization and spacing for the adjectives string in the names module.
=> Fix adjective frequencies in names module

src/pages/Welcome.js
Embarassingly, searching the puzzle repo accounts for a huge amount of the hosting costs of downforacross. this change should drastically reduce the amount of data being read from firebase.
---
the entire puzzle list is about 3MB, with ~10000 entries. The algorithm for search often behaves extremely inefficiently, because 
1. client-side filters the puzzle list items
2. fetches the last 1 page, then last 2 pages, then last 3 pages, until it has enough post-filter results to render the page up to where the user has scrolled to.
In total this means that doing a single search for a keyword like "foobar" will cause the client to download the entire puzzle list 10000 / 40 = 250 times, for a total of 600MB data transferred.
This PR reduces that worst case behavior to ~6MB (100x) by doubling the …
=> optimize puzzlelist: page geometrically instead of linearly

src/store/puzzlelist.js
a follow-up to https://github.com/downforacross/downforacross.com/pull/134, no one really needs more than the latest 4000 puzzles. at least for now.
=> make puzzle repo not all get downloaded

server/model/room.ts, src/lib/reducers/room.ts, src/pages/Room.tsx, src/shared/roomEvents.ts, src/style.css
the vision for rooms
- a permanent link that can hold multiple games -- so when you're done and want to play a new game, you don't need to paste a new link for everyone to join.
some immediate things that this unblocks
- users can bookmark a link like downforacross.com/team/stevens-crossword-friends-1
- gather.town integration
- public lobby rooms for people to meet other users on the platform. can link to these in homepage / pin to discord or whatever
- an archive of puzzles that a group has solved together
---
this pr might be broken into multiple PRs to allow incremental progress:
auto-join last game when join)
Room actions to support:
- addGame(gid) -- add gid to list of games that belong to this room.
- note: allows multiple rooms to share the same game. whatever.
- …
=> support room ids

server/sql/adhoc/sanitize_puzzles_1_24_21.sql
this was causing issues when filtering on puzzle json content.
this is a follow-up to https://github.com/downforacross/downforacross.com/pull/149
=> sanitize puzzles for pg unsupported unicode sequence

server/sql/adhoc/migrate_puzzles_content_1_24_21.sql
a follow-up to https://github.com/downforacross/downforacross.com/pull/148
```
psql -c '\d puzzles' 
Table "public.puzzles"
Column    |            Type             | Collation | Nullable | Default 
-------------+-----------------------------+-----------+----------+---------
uid         | text                        |           |          | 
pid         | text                        |           | not null | 
is_public   | boolean                     |           |          | 
uploaded_at | timestamp without time zone |           |          | 
content     | jsonb                       |           |          | 
Indexes:
"puzzles_pkey" PRIMARY KEY, btree (pid)
PGDATABASE=production psql -c '\d puzzles'
Table "public.puzzles"
Column    |            Type             | Collation | Nullable | …
```
=> migrate column content to jsonb

src/components/PuzzleList/NewPuzzleList.tsx
The new puzzle list search was always lagging behind by one character type which was not ideal.
This is fixed by making the react callback actually depend on the filters which will make the search match all of the current filters, because we will reload whenever the filter changes.
We JSON stringify as react compares with === so if we do not then it will change on every render rather than only then the filters actually change.
=> Fix search

src/components/Upload/FileUploader.js, src/components/Upload/Upload.js
Currently, upon uploading an invalid .puz file, the upload silently fails with the unhandled exception or error showing up in the console as seen below.
- ![image](https://user-images.githubusercontent.com/6465531/109259729-d379b500-77ca-11eb-99bc-8003566ad33a.png)
- ![image](https://user-images.githubusercontent.com/6465531/109263209-e1323900-77d0-11eb-9aa2-49e485d314ff.png)
The modals from these changes should add better feedback for the following 2 cases.
**1. When the file _is not_ in valid .puz format, this modal is shown.**
**2. When the file _is_ in valid .puz format, but the parsed puzzle is not a valid puzzle, this modal is shown.**
=> Show better feedback when a user uploads an invalid .puz file

src/style.css
As of Chrome 53, the `will-change` CSS property will cause objects to not re-rasterize after a `transform` is applied. This causes the side effect of blurry images and texts. Read more about the issue here:
- https://googlechrome.github.io/samples/css-will-change-transform-rasterization/
- https://greensock.com/will-change/
- https://stackoverflow.com/a/54082690
The SweetAlert library uses the `will-change` property to optimize their animations, but this causes an undesirable side-effect as the text, buttons, and edges of modals appear to be blurry. This change overrides the default CSS of SweetAlert to fix this. Take note of the subtle differences below (on Chrome 88.0.4324.190).
Before:
After:
=> Fix blurry modals by overriding will-change property

src/components/common/Nav.js, src/components/common/css/nav.css
Added an information 'i' icon to the nav bar.
Clicking on the icon will pop up a modal with information about the site, including a link to the Discord and this GitHub.
Tested on desktop and on mobile, and this change also inadvertently fixes the search bar flex-grow/shrink that wasn't working on mobile. The 'secret' button remains to the left of the info button. The 'Log In' button, if visible, is to the right of the info button.
=> Add info modal with links to Discord and GitHub

src/components/Player/GridControls.js, src/components/Toolbar/index.js
This PR makes it possible to move cursor perpendicular to current orientation without changing orientation, using the same keyboard shortcuts as Across Lite (Shift-Arrow). Requested in #164
=> Add Shift-Arrow keyboard navigation for perpendicular cursor movement

package.json, yarn.lock
The `{KEY}={VALUE}` syntax used to set environment variables does not work for Windows. Instead, the `set` keyword must be used as such: `set PORT=3020`. Instead of having 2 start scripts (like `yarn start` and `yarn start-windows`) to account for this difference, we can use [cross-env](https://www.npmjs.com/package/cross-env) to have a single start command without worrying about the operating system.
=> Use cross-env to make yarn start work for Windows

package.json, src/actions.js, src/components/PuzzleList/NewPuzzleList.tsx, src/components/PuzzleList/PuzzleList.js, src/components/Toolbar/index.js, src/components/Upload/FileUploader.js, src/components/Upload/Upload.js, src/components/Upload/css/fileUploader.css, src/components/common/Nav.js, src/components/common/css/nav.css, src/pages/Welcome.js, src/pages/css/welcome.css, src/style.css, yarn.lock
Uploading a puzzle should appropriately show the right modals on successful validation, where you can choose unlisted or public. Also refreshes the puzzles list upon confirming a public upload. Also some prettier CSS with the drag and drop.
After selecting a file to upload:
After selecting the upload button:
After choosing unlisted and selecting the upload button:
By using the [@sweetalert/with-react](https://www.npmjs.com/package/@sweetalert/with-react) package, I was also able to remove some helper functions from the modals and allow for more extensibility and customization to the modals.
=> Added modals for uploading puzzles

src/components/Grid/Grid.tsx
toCellIndex requires number of columns, but the number of rows was being passed in, leading to the circles being the wrong place. Passing in grid[0].length fixes this. Addresses #122 and #183.
=> Fix incorrect circle markups in some puzzles

src/lib/jsUtils.js
Hello again!
Since my previous pull request, I realised that part of why my experience on iPad has been so degraded is that the "desktop" version of downforacross was never intended to support devices without a hardware keyboard.
With the introduction of iPadOS, it seems iPads stopped reporting themselves as iPads (by default).  Instead, they report themselves identically to mac devices, unless a "request desktop site" option is disabled.
With that knowledge, as a user, I discovered that I can toggle that setting and get access to the mobile version of downforacross.  👍 
I decided to push this pull request, but I'm not certain it's a good idea.
This pull request updates the mobile detection logic to more reliably identify iPadOS by looking at the presence of touchscreen support in …
=> iPad OS no longer reports platform as iPad, by default

src/components/Grid/Cell.tsx
Fixes #181
After a simple touch event, modern mobile browsers fire a simulated "click" event.  I believe what's happening in this issue is that _both_ the `click` _and_ `touchend` event handlers are calling `onClick` for each tap on the screen.  This causes the state to flip from row to column mode and back.
There are more than one approach to fixing this issue:
1. At smaller screen sizes, when this app's extra "mobile" features kick in, this issue is no longer present. Activate that mode earlier, or port whatever logic changed between modes back to the tablet.
2. In  the `touchend` event handler, just before calling `onClick`,  call e.preventDefault().  This prevents the touch event from generating a simulated click event.
However, it strikes me that the "click" event generated by …
=> Fix: Can't toggle selected direction on tablet

src/components/Player/Player.js, src/lib/wrappers/GridWrapper.js
Updates logic for setting the initially selected squares on puzzle load.
Selects first available 'across' clues, and then first available 'down' clues. Defaults to selecting {0,0} if none found. For example, if a puzzle does not have 1A, but has 4A (see https://downforacross.com/beta/game/1083156-trag), the 4A squares will be selected on page load.
Handles edge cases where puzzles:
-Don't have 1A clue
-Don't have any across clues
-Don't have any clues (though we should not allow such puzzles to be uploaded in the first place)
Should address #199 and #203.
=> Update logic for setting initial selected squares

src/components/Game/Game.js, src/components/Player/GridControls.js, src/components/Player/Player.js, src/components/Toolbar/index.js
Adds keyboard shortcuts for check/reveal square, word, and puzzle. No confirmation dialog.
Alt + S, W, or P - Check square, word, or puzzle
Alt + Shift + S, W, or P - Reveal square, word, or puzzle
=> Add keyboard shortcuts for check/reveal

src/components/Player/ClueText.js
Partially addresses #220 . Decoding HTML encoded clue values. Very unsure if this is the _best_ way to fix this, but it does appear to work 😄 
The puzzle provided in #220 does have a few examples of this but it doesn't appear I can upload that puz file to the issue 😢
=> Decode HTML in Clues

src/components/Player/MobileGridControls.js
Bound the comma key on a mobile keyboard to replicate the behavior of tab on web. Moving between clues is cumbersome without it (in my opinion of course 😄 ).
I'm completely unsure if this is the right way to go about suggesting a change like this so please let me know!
=> Mobile Control Enhancement

src/components/Game/Game.js, src/components/Grid/Cell.tsx, src/components/Grid/Grid.tsx, src/components/Grid/types.ts, src/components/ListView/ListView.tsx, src/components/ListView/css/listView.css, src/components/ListView/index.ts, src/components/Player/GridControls.js, src/components/Player/ListViewControls.tsx, src/components/Player/MobileGridControls.js, src/components/Player/MobileListViewControls.tsx, src/components/Player/Player.js, src/components/Player/css/index.css, src/components/Toolbar/css/ActionMenu.css, src/components/Toolbar/css/index.css, src/components/Toolbar/index.js, src/lib/wrappers/GridWrapper.js
Adds a "Clue List View" similar to the NYT crossword app.
- Adds a `ListView` component and renders it in `Player`, based on a new `listMode` toolbar button
- Adds a `ListViewControls` component which extends the `GridControls` component, and alters the direction handling to make movement fluent with the cell layout in list view
- Adds a `MobileListViewControls` component which extends the `MobileGridControls` component, alters the direction handling to make movement fluent with the cell layout in list view, and overrides the touch interaction to allow for natural scrolling
=> Implement ListView and ListViewControls

src/components/Player/ClueText.js
This accounts for clues which may not include spaces, such as `What_the_underlines_in_this_clue_show` on May 23, 2022.
before
after
bonus: it looks like the print edition of the NYT broke this on an actual underscore
=> Add "word-break: break-word;" to cluetext

src/components/Chat/css/index.css
Changed `margin-bottom: 10px;` to a `margin: 5px;` to add a little more space around system chat messages. I didn't like how close the message was to the horizontal bar below the player names. No one really asked for this, but I think it looks nicer 🤠 If there are more system messages to be added in the future, this will come in handy.
Before:
After:
=> Tweak margin around chat system messages

src/components/Toolbar/css/index.css
Fixes double border caused by the toolbar and chat.
Before:
After:
=> Remove border-right on toolbar

.envrc.template, package.json, server/README.md
Adding `cross-env` to the npm scripts sections for `devfrontend` and `devbackend`. I presume these will need to be added for the other scripts as well, but just adding these in for now.
Also making a note about DirEnv since it does not come pre-packaged with Windows, and added a few more env variables that might cause issues if not automatically set. For reference, the following error is returned if the PGUSER/PGPASSWORD is not set.
```
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received null
```
=> Make backend development more windows-friendly

src/components/Grid/Cell.tsx, src/components/common/css/nav.css, src/dark.css
Make some changes to dark mode colors following some guidelines from [https://m2.material.io/design/color/dark-theme.html](https://m2.material.io/design/color/dark-theme.html):
- Changed all primary text to white with 87% opacity
- Changed background to #121212
- Use 5% overlay for "elevated surfaces" and 12% for "menu surfaces" and the grid
- Use 47% opacity instead of the recommended 38% opacity for "disabled" text to maintain a 4.5:1 contrast ratio
Other color changes include
- Make black squares black and normal grid squares lighter.
- Make the selected square the users color
- Add a darker version of the referenced color
- Make highlighted row green on completion
- Modify some other colors to look better (in my opinion)
Also fixed an issue with the dark mode selection changing the …
=> Change dark mode colors

src/components/Game/Game.js
Removes check for mobile when deciding to display confetti. Previously it wouldn't display confetti when on mobile, now always displays it.
Per issue #260 there seems to be consensus that performance issues are no longer a concern for mobile users. And confetti is fun! So let's turn it on : )
=> Turn on confetti for mobile solves

package.json, src/index.js, src/lib/hooks/useStateParams.ts, src/pages/Welcome.js, src/pages/WrappedWelcome.tsx, src/pages/index.js, tsconfig.json, yarn.lock
The changes in this PR persist the current search query and filter options of the Welcome page in the URL params, which allows users to link to a version of the Welcome page with a specific pre-populated search query and/or filter options. This is mainly designed to accommodate users that bookmark/pin a tab for [downforacross.com ](url) and are only interested in viewing New puzzles that fit a certain search string, and don't want to look through the full list of puzzles or enter a search string when they open/refresh the page.
https://user-images.githubusercontent.com/14168765/231033457-31af2697-69ea-4021-9387-f011895c302e.mp4
=> Store search query and filter options state in URL params

src/components/Upload/FileUploader.js, src/lib/converter/iPUZtoJSON.js, src/lib/fileTypeGuesser.js
This PR adds fairly robust support in for iPUZ files, along with some utility classes to hopefully detect other crossword filetype support in the future (e.g. `jpz`).
Will add more comments inline in the PR soon!
Relevant background on iPUZ: http://www.ipuz.org/
See also #246
=> Add in iPUZ support

src/components/common/Nav.js
The dark mode toggle is now persistent when dark mode is enabled because it is a beta feature. It should be hard to turn on but easy to turn off.
=> Show dark mode toggle when dark mode is enabled

src/components/Toolbar/index.js
I have, on several painful occasions, accidentally misclicked "Reset > Puzzle" rather than "Reset > Word". This PR adds a confirmation dialog before taking the Reset action at the Puzzle level 😅
=> Show a confirmation dialog before resetting the entire puzzle

middleware.ts, server/api/link_preview.ts, server/api/oembed.ts, server/api/router.ts, server/model/game.ts, utils/link_preview_util.ts
This PR implements a feature that generates link previews (also known as "embeds") for DFAC game URLs (e.g. `https://downforacross.com/beta/game/1234567-joct`) sent in platforms such as Discord and Slack. These previews are generated by "link unfurling" crawlers on these platforms that visit the URLs posted in sent messages and search for certain tags.
Using [Vercel Middleware](https://vercel.com/docs/concepts/functions/edge-middleware), requests can be intercepted before the response is served, and if the request URL is a game URL, and if user-agent string is suggestive of a crawler, the crawler can be redirected while human users are unaffected. Crawlers are redirected to an [API endpoint ](https://github.com/shintyl/downforacross.com/blob/f11bf29120d8cdaff9575aef901995e9f5a6e7da/server/ …
=> Implement link previews

server/api/link_preview.ts
Fix minor issue seen in https://github.com/downforacross/downforacross.com/pull/284#issuecomment-1673702485 where Messenger link previews contained an unnecessary vertical bar if the description was empty.
Missing descriptions should look like this now:
=> Fix Messenger link preview formatting

README.md, src/components/Player/Player.js, src/pages/Replay.js
Inspired by https://github.com/downforacross/downforacross.com/issues/286
Shows the number of squares filled in by each player at each point on the Replay timeline
When scrubbed to the end of the Replay timeline, this will be the number of squares solved by each player
=> Show number of squares filled by each user in Color Attribution Mode

src/components/Game/Game.js, src/components/Toolbar/Clock.js, src/components/Toolbar/css/index.css, src/components/Toolbar/index.js
In response to #288 I tried my hand at a solution by adding a menu expansion toggle to reveal the icons that were being shrunk.
- Added state variable to toggle between menus
- Added icon that shows/hides the alternative menu items on tap
- Called to update clock when mounted (otherwise it would show 00:00 for a second when toggling between menus)
Show toggle hides and reveals the correct menu items as expected, and that the menu items still work:
=> add menu toggle for mobile

src/components/Chat/Chat.js, src/pages/Game.js
This fixes the bug where mobile users don't get assigned a username until they open the chat. This happens because the usernames are initialized in the `Chat` component, but for mobile, the `Chat` component is not mounted until it is opened.
This PR fixes this issue by creating an `initialUsername` and updating the user's username to this value when the `Game` component mounts.
This fixes #272.
=> Fix mobile username issue

src/components/Game/Game.js
Resolves #291.
This PR adds local storage for the vim mode toggle to be used in the state of the `Game` component. This avoids the need to enable Vim mode every time the crossword is loaded.
Tested locally and on preview.
=> Local storage for vim mode

src/components/Toolbar/index.js
This PR automatically saves the user's pencil color, so it will no longer reset to gray on page reload or when starting a new puzzle.
=> Persist pencil color

src/components/Chat/Chat.js, src/lib/nameGenerator.js, src/pages/Game.js
This code change adds a `default_username` to the localStorage that is only set when the user updates their username to something that is not a randomly generated name. This value is then checked when other games are loaded and if it is set, is used instead of the randomly generated name.
Here's the state of local storage after a new game is created:
Here's the state of local storage after the username is updated:
Here's the state of a new game after the `username_default` is set:
=> Added a default username that persists across games when set

src/components/Toolbar/css/index.css, src/components/Toolbar/index.js
This adds the autocheck button to the expanded menu on the mobile toolbar with updated styling to make its state visible above the blue menubar.
=> Add autocheck button to mobile toolbar.

src/components/Grid/Cell.tsx, src/components/Player/GridControls.js, src/components/Player/css/gridControls.css
This fixes #192, allowing using the non-mobile interface on devices without keyboards as having a focused input field triggers the virtual keyboard on devices that need it.
=> Create and focus an invisible input field on click.

src/components/Player/MobileGridControls.js
From reading the code, I've inferred that the input box has a well-defined initial state that we always reset to: It has a value of "$", and the cursor is always at the end.
In cases where the cursor is NOT at the end as expected, we see two error cases:
- User enters a letter, the change handler fires with input like "a$", and "$" is incorrectly entered in the grid.
- User attempts to backspace, and the change handler does not fire at all because the cursor was at position 0 (Fixes #317)
I've developed and tested this fix using an android emulator attached to a chrome debug window.
=> Fix backspace behavior on mobile.

src/components/Chat/Chat.js, src/components/common/EditableSpan.js
I do the crossword every morning with my friends. When I do it on mobile, I can't set my username so I always have to awkwardly leave a chat message saying my name
This PR fixes that!
Disclaimer: this is technically untested, because staging API is hanging, but I edited the HTML locally on prod to produce the same effect, and it worked great.
=> Allow username editing on mobile

src/components/Fencing/FencingScoreboard.tsx
Hi! This is my first PR on github, let me know if I'm doing it right or if there's a test suite or something like that.
This commit just adds a simple win indicator for fencing because right now it's very annoying that the fencing will end and neither team knows who won or gets to see the board.
If you would prefer a bigger commit, I'm hoping to add some other improvements to fencing on this branch after I get free in a couple weeks or so, but I'd like to merge this in so I can have more fun playing fencing with my friends in the meantime.
The specific content of this fix is in `src/components/Fencing/FencingScoreboard.tsx`, where I added a winIndicator `span` next to the winning team name that says "🏆 Winner!". It displays only if every cell is filled.
=> win indicator for fencing
